name: Docker Image CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'releases/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Variable using Shell Command
      run: |
          VERSION=$(cat ./VERSION)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images with latest tag
      uses: docker/build-push-action@v6.13.0
      with:
        build-args: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          VCS_REF=$(git rev-parse HEAD)
          VERSION=$(cat VERSION)
        push: true
        tags: localgod/jmeter:latest
    - name: Build and push Docker images with version tag
      uses: docker/build-push-action@v6.13.0
      with:
        build-args: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          VCS_REF=$(git rev-parse HEAD)
          VERSION=$(cat VERSION)
        push: true
        tags: localgod/jmeter:${{ env.VERSION }}

